name: github-pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    concurrency: ci-${{ github.ref }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6
      
      - name: Install Haxe Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib git haxeui-core https://github.com/haxeui/haxeui-core 0212d8fdfcafeb5f0d5a41e1ddba8ff21d0e183b
          haxelib git haxeui-flixel https://github.com/haxeui/haxeui-flixel 63a906a6148958dbfde8c7b48d90b0693767fd95
          haxelib install tjson
          haxelib git hscript https://github.com/HaxeFoundation/hscript
          haxelib install rulescript
          haxelib install hxluajit
          haxelib install hxluajit-wrapper
          haxelib git scriptless-polymod https://github.com/JoaTH-Team/scriptless-polymod
          haxelib git thx.core https://github.com/fponticelli/thx.core.git
          haxelib install thx.semver
          haxelib git jsonpath https://github.com/EliteMasterEric/jsonpath.git
          haxelib install jsonpatch
          haxelib install hxgamemode
          haxelib install hxdiscord_rpc
          haxelib install hx_arabic_shaper
          haxelib install hxcpp-debug-server
          haxelib install dox
          haxelib install format
          haxelib list
      
      - name: Create Documentation Site
        run: |
            chmod +x docs/docs.sh
            docs/docs.sh
      
      - name: github-actions deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: pages
          token: ${{ secrets.GH_PAT }}